### ISSUE TITLE
Genotype Inputs

### ISSUE THREAD

**Issue by quattro** [mancusolab/sushie#14]
Lets stress test genotype inputs when there is missing data, and a few other sanity checks.

- [x] VCF should use `VCF(..., gts012=True)` and `gt_types` to pull genotype information and check for missing (see https://brentp.github.io/cyvcf2/docstrings.html)
- [x] Bgen is unclear as to which allele is being represented as 0/1, and typically requires that info upfront (see https://www.cog-genomics.org/plink/2.0/input#oxford for how PLINK2 handles this)
- [x] Let's do naive imputation at missing alleles (i.e. use 2 * freq) and be clear about that in documentation somewhere

**Comment by zeyunlu** [comment]
I don't have test data that has missing allele in bgen, vcf, or plink. How do I make some?

**Comment by quattro** [comment]
@zeyunlu , for PLINK-1 bfile data, see how to handle/impute missing calls [here](https://github.com/bogdanlab/fizi/blob/34d08fe9564d14ff313f2d4a06bfc843f33b8bf5/pyfizi/ref.py#L151).

**Comment by zeyunlu** [comment]
For imputation, I add impute function [here](https://github.com/mancusolab/sushie/commit/79a0a553c43cc0d7ff32dc48bccc1852abbced40?short_path=eb32f8b#diff-eb32f8bddc160a55758fd0af5037778bb800ec1b2431e404660faf56fcee6fc2)

and I also update the documentation. Usually, we impute them beforehand, but it's good to have it as a sanity check.

For the bgen issue, according to the documentation,  bgen.read() gives unphased biallelic genotype in either (1,0,0), (0,1,0), or (0,0,1) where the first one means homozygous of allele A, the second means hetero, the third means homozygous of allele B.

If we make sure the allele B is the reference allele, we can use `jnp.einsum("ijk,k->ij", bgen.read(), jnp.array([0, 1, 2]))` to get our genotype matrix, for now, I think we can just ask users to make sure that the latter allele (allele B) is the reference allele.
