### ISSUE TITLE
Minor tweak to PIP computation

### ISSUE THREAD

**Issue by quattro** [mancusolab/sushie#24]
We can improve the numerical stability of PIP computation by going from 
```python
pip = 1 - jnp.exp(jnp.sum(jnp.log1p(-alpha), axis=0))
```
to
```python
pip = -jnp.expm1(jnp.sum(jnp.log1p(-alpha), axis=0))
```

It probably won't affect much, and may be overkill, but comes at no additional computational cost, and should see slight benefit when the summed log probabilities are small.

**Comment by zeyunlu** [comment]
done!
