### ISSUE TITLE
Incorrect sample size reported in sushie.cv.tsv 

### ISSUE THREAD

**Issue by Xinyu-Sun** [mancusolab/sushie#42]
Hello,

I encountered an issue with the cross-validation output, specifically regarding the reported sample size. It appears that the sample size reported is always that of the last ancestry processed.

You can reproduce the problem using the following test data:

```
sushie finemap
	--pheno EUR.pheno
	        AFR.pheno
	--plink plink/EUR
	        plink/AFR
	--covar EUR.covar
	        AFR.covar
	--cv
	--her
	--output ./test_result
```

The `test_result.sushie.cv.tsv` output looks like this:
| ancestry | rsq                | p_value                | N   | trait |
| :------- | :----------------- | :--------------------- | :-- | :---- |
| 1        | 0.4932215908291845 | 4.133847921724767e-74  | 639 | Trait |
| 2        | 0.4743709425200131 | 3.0193789659893506e-91 | 639 | Trait |

As shown above, both ancestries have the same reported sample size of 639. However, based on the input files, I would expect the EUR ancestry to have 489 samples. 

Xinyu

**Comment by zeyunlu** [comment]
Sorry, I didn't see this until now. 

Nice catch! Will fix it in the next version. I probably get it fixed by the end of the coming week.

Thank you so much! For future immediate questions, please email me as I usually do not watch the issue section every day!

Thank you!

Best,
Zeyun
